#!/bin/bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then  
  echo "Usage: 'basename $0' [The correct way to run the script is: ./config_monit 'IP Address of Server' 'Log Email Address']" | exit 0 ; 
else
echo "Now installing Monit..." 
yum -y install epel-release
yum -y install monit
echo "Now Configuring Monit..."
wget https://github.com/SpencerSchwartz/a3/raw/main/client_config | tee -a monit-install.log
mv client_config /etc/ && cp /etc/client_config /etc/monitrc && chmod 600 /etc/monitrc 
sed -i "s/root@localhost/root@$1/g" /etc/monitrc && sed -i "s/alert emailhere/alert $2/g" /etc/monitrc 
echo "Now restarting Monit..." && systemctl restart monit && echo "Monit now configured" 
echo "Now setting up remote monitoring..." && sed -i "s/#*.* @@remote-host:514/*.* @$1:514/g"  
systemctl restart rsyslog
echo "Remote monitoring now configured" 
firewall-cmd --zone=public --add-port=514/udp --permanent | tee -a monit-setup.log
firewall-cmd --zone=public --add-port=2812/tcp --permanent | tee -a monit-setup.log
firewall-cmd --reload 
yum -y install sendmail
systemctl start sendmail
systemctl start monit
fi
