#!/bin/bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then  
  echo "Usage: 'basename $0' [The correct way to run the script is: ./config_monit 'IP Address of Server' 'Log Email Address']" | tee -a monit-install.log ; exit 0 ; 
else
echo "Now installing Monit..." 
yum -y install epel-release
yum -y install monit
echo "Now Configuring Monit..." | tee -a monit-install.log && rm /etc/monitrc >& 1 >> monit-install.log
wget https://github.com/SpencerSchwartz/a3/raw/main/client_config | tee -a monit-install.log
mv client_config /etc/ && cp /etc/client_config /etc/monitrc >& 1 >> monit-install.log && chmod 600 /etc/monitrc >& 1 >> monit-install.log &&
sed -i "s/root@localhost/root@$1/g" /etc/monitrc >& 1 >> monit-install.log && sed -i "s/alert emailhere/alert $2/g" /etc/monitrc >& 1 >> monit-install.log &&
echo "Now restarting Monit..." | tee -a monit-install.log && systemctl restart monit >& 1 >> monit-install.log && echo "Monit now configured" | tee -a monit-install.log
echo "Now setting up remote monitoring..." | tee -a monit-install.log && sed -i "s/#*.* @@remote-host:514/*.* @$1:514/g" /etc/rsyslog.conf >& 1 >> monit-install.log && 
systemctl restart rsyslog >& 1 >> monit-install.log && 
echo "Remote monitoring now configured" | tee -a monit-setup.log 
firewall-cmd --zone=public --add-port=514/udp --permanent | tee -a monit-setup.log
firewall-cmd --zone=public --add-port=2812/tcp --permanent | tee -a monit-setup.log
firewall-cmd --reload | tee -a monit-install.log
yum -y install sendmail
systemctl start sendmail
systemctl start monit
fi
